version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH_1302Project
  gitServerName: srcCtrl_github_Sourabh_shared
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: main
- name: LowerFSPackage
  gitServerName: srcCtrl_github_Sourabh_shared
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: sourabh-harkawat-0058QC744
  gitBranch: main
- name: GithubPackageDebuglog
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
